\documentstyle[11pt,norsk]{article}

\title{Hovedprosjekt 08}
\author{M Byhring, T E Iversen, L M Bredal\\
Høyskolen i Oslo, avdeling for ingeniørutdanning}
\renewcommand{\today}{26 februar, 2008}
\maketitle

\begin{document}
\part {Prosessdokumentasjon}
\section {Presentasjon}
Som for forprosjektrapport
\section {Om bakgrunnen}
Kort om bakgrunnen - litt om bedrift, situasjon og hensikten med
produktet, men kortere enn i forprosjektrapport. Eventuelle hovedtrekk
ved kravspesifikasjonen
\section {Forord}
Hensikten med kravspesifikasjonen. Hvem kravspesifikasjonen er
beregnet for. Kort om hvilken rolle den har spilt i prosjektet. (Mer om
dette må plasseres i prosessdokumentasjonen)
\section {Leserveiledning}
Hvordan kravspesifikasjonen er organisert
\section {Kort systembeskrivelse}
med de forbedringer en venter å oppnå \\
Systemets funksjonelle egenskaper, beskrevet ved diagrammer og
prosess-spesifikasjoner osv.
\section {Rammekrav i systemet, f.eks.}
\begin{itemize} 
\item sikring mot tap, ødeleggelse, tyveri og misbruk av data
\item kapasitet
\item fremtidig utvidelse av systemet
\item bruk og brukervennlighet
\end{itemize}
\section {Logisk datamodell}
\section {Eventuelle krav til systemkonstruksjon}
\section {Eventuelle krav til dokumentasjon}
\section {Eventuelle krav til manuelle funksjoner}
\section {Dataordbok}



\end{document}
