\documentclass[11pt,a4paper]{report}
\usepackage[latin1]{inputenc}
\usepackage[norsk]{babel}


\begin{document}
\title{Hovedprosjekt 08}
\author{M Byhring, T E Iversen, L M Bredal\\
Høgskolen i Oslo, avdeling for ingeniørutdanning}
\renewcommand{\today}{26 februar, 2008}
\maketitle

\section*{Innledning}
Her vil det komme en innledning etter hvert\\

LCFG er et system ++++

\section*{Hoveddel}

\subsection*{Innledning}
Det kan tenkes at innledningen på Hoveddelen ikke får noen tittel, slik som den har nå. Vi får se.

\subsection*{Planlegging og metode}
\begin{itemize}
\item XML-filene
\item Verktøy: Perl, MySQL, SVN, VRML, eclipse, VRMLPad +++++
\item Faglige forutsetninger
\item Hva måtte vi lære oss?
\item Databasestruktur
\item Hva vi skulle visualisere. Hvorfor og hvordan
\item Visualiseringstype
\end{itemize}



\section*{Avslutning}


\end{document}
